sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IiETG/nf5yAtQY8/XAyVW3HMfjFAkcT0V6Wi17N7TUOmgqa+aurB+fU2MXVzYC1FzYpFX6Fr30l/MflIeY4u3E3tl42JwVm5fhHqCrRRJy8VWpGfo/vrs9ccpfN7DbIvTTV+hSmy7cD9VjzpJWfGJF62jGgGs7sCPX+0nY2dc1J/cGarsbVv/apcZidDalHCRYw/x45rN8oa3Ip/x380vh9E9wImDQvJDbMTbT0vxoI1Mgtl91Zj9c7Tu1LKwAT5rIv5VSOVWk5Ylf2ibnOFr7zEQ+T/SrUziTpEy0D8hX5xG6bSuG1qKD5wVl8FSrwqnDFChyJqigWrgh0bdATTKvU/0f6FnPlScVbxdRmt3EFnjFGIqQW74u4WAPOUUCgn3gcZVIt3JQ8IiQgDSQZ1K87vYTaZBUdz3NC5ZAOTXPDDfBe7usAOCLQ7ZAKGBXriP+GpZkiY6DjXZSrzXK2tqKoUtbOG+4tnTpF+YD5wOqAhhmgnWAUEdsoT+EJ9MJL8vH6UhbYmMIjwSVJZABZEShsh3APUgcXjWwQHq65fh5Qn+jtzvOJ/BXLDBAYcu935P2Sch3frdEzM3HrJJt+uB+rGgWdbZOg2/mrMKKJ20qxyA3X2GbVDzVRr+p8YhWkZ1ymIaa+4HI+onKv1xo7I7ALDSAc9LeYngwQfXFXlKss=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Lay-of-the-Cid_6088
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy